from __future__ import annotations

from enum import Enum
from typing import Any


class ErrorCode(str, Enum):
    OK = "OK"
    E400_BAD_REQUEST = "E400_BAD_REQUEST"
    E400_INVALID_ARGUMENT = "E400_INVALID_ARGUMENT"
    E400_INVALID_SCOPE = "E400_INVALID_SCOPE"
    E400_MISSING_SHEET_NAME = "E400_MISSING_SHEET_NAME"
    E400_INVALID_COLOR = "E400_INVALID_COLOR"
    E400_INVALID_SHEET_NAME = "E400_INVALID_SHEET_NAME"
    E400_ROW_OUT_OF_RANGE = "E400_ROW_OUT_OF_RANGE"
    E400_COLUMN_OUT_OF_RANGE = "E400_COLUMN_OUT_OF_RANGE"
    E400_EMPTY_VALUES = "E400_EMPTY_VALUES"
    E400_RANGE_INVALID = "E400_RANGE_INVALID"
    E400_FORMULA_INVALID = "E400_FORMULA_INVALID"
    E400_INVALID_SORT_KEY = "E400_INVALID_SORT_KEY"
    E400_SORT_RANGE_CONFLICT = "E400_SORT_RANGE_CONFLICT"
    E400_MERGE_RANGE_INVALID = "E400_MERGE_RANGE_INVALID"
    E400_ALREADY_MERGED = "E400_ALREADY_MERGED"
    E400_NO_MERGED_CELLS = "E400_NO_MERGED_CELLS"
    E400_VBA_MODULE_NAME_INVALID = "E400_VBA_MODULE_NAME_INVALID"
    E400_VBA_CODE_TOO_LARGE = "E400_VBA_CODE_TOO_LARGE"
    E403_PATH_NOT_ALLOWED = "E403_PATH_NOT_ALLOWED"
    E403_FEATURE_NOT_ALLOWED = "E403_FEATURE_NOT_ALLOWED"
    E403_SHEET_PROTECTED = "E403_SHEET_PROTECTED"
    E403_VBA_ACCESS_DENIED = "E403_VBA_ACCESS_DENIED"
    E403_VBA_PROJECT_PROTECTED = "E403_VBA_PROJECT_PROTECTED"
    E403_VBA_POLICY_BLOCKED = "E403_VBA_POLICY_BLOCKED"
    E404_WORKBOOK_NOT_OPEN = "E404_WORKBOOK_NOT_OPEN"
    E404_SHEET_NOT_FOUND = "E404_SHEET_NOT_FOUND"
    E404_SNAPSHOT_NOT_FOUND = "E404_SNAPSHOT_NOT_FOUND"
    E404_VBA_MODULE_NOT_FOUND = "E404_VBA_MODULE_NOT_FOUND"
    E404_NAMED_RANGE_NOT_FOUND = "E404_NAMED_RANGE_NOT_FOUND"
    E409_FILE_EXISTS = "E409_FILE_EXISTS"
    E409_FILE_LOCKED = "E409_FILE_LOCKED"
    E409_SHEET_NAME_EXISTS = "E409_SHEET_NAME_EXISTS"
    E409_WORKBOOK_READONLY = "E409_WORKBOOK_READONLY"
    E409_WORKBOOK_DIRTY = "E409_WORKBOOK_DIRTY"
    E409_WORKBOOK_VBA_UNSUPPORTED = "E409_WORKBOOK_VBA_UNSUPPORTED"
    E409_SNAPSHOT_EXPIRED = "E409_SNAPSHOT_EXPIRED"
    E409_BACKUP_EXPIRED = "E409_BACKUP_EXPIRED"
    E409_PREVIEW_TOKEN_INVALID = "E409_PREVIEW_TOKEN_INVALID"
    E409_CANNOT_DELETE_LAST_SHEET = "E409_CANNOT_DELETE_LAST_SHEET"
    E409_CONFIRM_TOKEN_INVALID = "E409_CONFIRM_TOKEN_INVALID"
    E409_VBA_MODULE_EXISTS = "E409_VBA_MODULE_EXISTS"
    E409_VBA_MODULE_SYSTEM_PROTECTED = "E409_VBA_MODULE_SYSTEM_PROTECTED"
    E410_WORKBOOK_STALE = "E410_WORKBOOK_STALE"
    E503_EXCEL_WORKER_STOPPED = "E503_EXCEL_WORKER_STOPPED"
    E503_EXCEL_REBUILD_LIMIT_REACHED = "E503_EXCEL_REBUILD_LIMIT_REACHED"
    E503_RUNTIME_UNAVAILABLE = "E503_RUNTIME_UNAVAILABLE"
    E503_RUNTIME_TIMEOUT = "E503_RUNTIME_TIMEOUT"
    E413_RANGE_TOO_LARGE = "E413_RANGE_TOO_LARGE"
    E415_EXTENSION_UNSUPPORTED = "E415_EXTENSION_UNSUPPORTED"
    E415_XLS_FORMAT_LIMIT = "E415_XLS_FORMAT_LIMIT"
    E423_FEATURE_NOT_SUPPORTED = "E423_FEATURE_NOT_SUPPORTED"
    E423_NAMED_RANGE_NOT_A_REFERENCE = "E423_NAMED_RANGE_NOT_A_REFERENCE"
    E403_VBA_EXECUTION_BLOCKED = "E403_VBA_EXECUTION_BLOCKED"
    E404_VBA_PROCEDURE_NOT_FOUND = "E404_VBA_PROCEDURE_NOT_FOUND"
    E408_VBA_EXECUTION_TIMEOUT = "E408_VBA_EXECUTION_TIMEOUT"
    E409_VBA_EXECUTION_DISABLED = "E409_VBA_EXECUTION_DISABLED"
    E409_DYNAMIC_ARRAY_NOT_SUPPORTED = "E409_DYNAMIC_ARRAY_NOT_SUPPORTED"
    E409_NAMED_RANGE_EXISTS = "E409_NAMED_RANGE_EXISTS"
    E404_BAS_FILE_NOT_FOUND = "E404_BAS_FILE_NOT_FOUND"
    E400_UNSUPPORTED_EXTENSION = "E400_UNSUPPORTED_EXTENSION"
    E400_SAVE_AS_FORMAT_MISMATCH = "E400_SAVE_AS_FORMAT_MISMATCH"
    E400_REPLACEMENT_INVALID = "E400_REPLACEMENT_INVALID"
    E409_OPERATION_NOT_REVERSIBLE = "E409_OPERATION_NOT_REVERSIBLE"
    E409_NOTHING_TO_UNDO = "E409_NOTHING_TO_UNDO"
    E409_UNDO_EXPIRED = "E409_UNDO_EXPIRED"
    E409_VBA_COMPILE_UNAVAILABLE = "E409_VBA_COMPILE_UNAVAILABLE"
    E500_EXCEL_RECOVERING = "E500_EXCEL_RECOVERING"
    E500_EXCEL_UNAVAILABLE = "E500_EXCEL_UNAVAILABLE"
    E500_COM_REJECTED = "E500_COM_REJECTED"
    E500_COM_DISCONNECTED = "E500_COM_DISCONNECTED"
    E500_OPERATION_TIMEOUT = "E500_OPERATION_TIMEOUT"
    E500_SNAPSHOT_CREATE_FAILED = "E500_SNAPSHOT_CREATE_FAILED"
    E500_SNAPSHOT_RESTORE_FAILED = "E500_SNAPSHOT_RESTORE_FAILED"
    E500_BACKUP_FAILED = "E500_BACKUP_FAILED"
    E500_INTERNAL = "E500_INTERNAL"


class ExcelForgeError(Exception):
    def __init__(
        self,
        code: ErrorCode,
        message: str,
        *,
        details: dict[str, Any] | None = None,
    ) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        self.details = details or {}


def normalize_exception(exc: Exception) -> ExcelForgeError:
    if isinstance(exc, ExcelForgeError):
        return exc
    return ExcelForgeError(ErrorCode.E500_INTERNAL, str(exc))

